### ISSUE TITLE
Unknown Crash. (CRASH REPORT INCLUDED)

### ISSUE THREAD

**Issue by SacredSven** [studio-minus/madness-interactive-reloaded#106]
**Describe the bug**
I am unsure how this happened, but I can give you the crash report!

```
Madness Interactive Reloaded has crashed with crash ID Sydop
Game build: MIR, Version=0.48.4.0, Culture=neutral, PublicKeyToken=null
Engine build: Walgelijk, Version=0.29.1.0, Culture=neutral, PublicKeyToken=null
[Component dump path](c:\Users\johnw\AppData\Local\Temp\mir_Sydop_components.md)
[System dump path](c:\Users\johnw\AppData\Local\Temp\mir_Sydop_systems.md)
[Log path](c:\Users\johnw\AppData\Local\Temp\mir_Sydop.log)
Unhandled exception occurred
System.InvalidOperationException: There is no progress component in the scene, so you can't invoke Win
Stack trace

   at MIR.LevelProgressSystem.Win() in C:\Projects\madness-interactive-reloaded\src\MadnessInteractiveReloaded\Level\Systems\LevelProgressSystem.cs:line 159
   at MIR.MachinistLevelSystem.b__0_1() in C:\Projects\madness-interactive-reloaded\src\MadnessInteractiveReloaded\Level\Systems\MachinistLevelSystem.cs:line 70
   at MIR.MadnessUtils.<>c__DisplayClass30_0.<g__delay|0>d.MoveNext()
   at Walgelijk.RoutineScheduler.g__advance|5_0(<>c__DisplayClass5_0&) in C:\Projects\Walgelijk\Walgelijk\System\RoutineScheduler.cs:line 82
   at Walgelijk.RoutineScheduler.StepRoutines(Single dt) in C:\Projects\Walgelijk\Walgelijk\System\RoutineScheduler.cs:line 78
   at Walgelijk.Game.Start() in C:\Projects\Walgelijk\Walgelijk\System\Game.cs:line 263
   at MIR.MadnessInteractiveReloaded..ctor() in C:\Projects\madness-interactive-reloaded\src\MadnessInteractiveReloaded\MadnessInteractiveReloaded.cs:line 211
   at MIR.Program.Main(String mode, String input, String output) in C:\Projects\madness-interactive-reloaded\src\MadnessInteractiveReloaded\Program.cs:line 56
```

**Comment by dch-GH** [comment]
@mestiez This might be happening if someone goes from main menu -> Experiment -> `setlevel lvl_train_machinist`? Why else would the progress component not be present?

**Comment by zayphi** [comment]
the same crash is described in #88

**Comment by mestiez** [comment]
I think this happens because the routine that wins the level does not check if we're still in that level. See `MachinistLevelSystem.cs`

**Comment by dch-GH** [comment]
> I think this happens because the routine that wins the level does not check if we're still in that level. See `MachinistLevelSystem.cs`

Fixed in https://github.com/studio-minus/madness-interactive-reloaded/pull/110
