### ISSUE TITLE
Open/save file dialogues crashes on Linux

### ISSUE THREAD

**Issue by Technochips** [studio-minus/madness-interactive-reloaded#367]
**Describe the bug**
Assuming we've copied over the libnfd.so file, upon trying to import or export a character, the game crashes:
```
Unhandled exception occurred
System.EntryPointNotFoundException: Unable to find an entry point named 'NFD_Init' in shared library 'nfd'.
Stack trace

   at NativeFileDialogExtendedSharp.Native.NFD_Init()
   at NativeFileDialogExtendedSharp.Nfd.InitNfd()
   at NativeFileDialogExtendedSharp.Nfd.FileOpen(IEnumerable`1 filters, String defaultPath)
   at MIR.FileDialog.OpenFile(ValueTuple`2[] filters, String& path) in /home/technochips/madness-interactive-reloaded-pkg/src/madness-interactive-reloaded/src/MadnessInteractiveReloaded/Shared/FileDialog.cs:line 17
   at MIR.CharacterCreationSystem.DrawButtons(CharacterCreationComponent data, CharacterComponent character) in /home/technochips/madness-interactive-reloaded-pkg/src/madness-interactive-reloaded/src/MadnessInteractiveReloaded/Character creation/Systems/CharacterCreationSystem.cs:line 222
   at MIR.CharacterCreationSystem.Update() in /home/technochips/madness-interactive-reloaded-pkg/src/madness-interactive-reloaded/src/MadnessInteractiveReloaded/Character creation/Systems/CharacterCreationSystem.cs:line 55
   at Walgelijk.Game.Start() in C:\Projects\Walgelijk\Walgelijk\System\Game.cs:line 230
   at MIR.MadnessInteractiveReloaded..ctor() in /home/technochips/madness-interactive-reloaded-pkg/src/madness-interactive-reloaded/src/MadnessInteractiveReloaded/MadnessInteractiveReloaded.cs:line 218
   at MIR.Program.Main(String mode, String input, String output) in /home/technochips/madness-interactive-reloaded-pkg/src/madness-interactive-reloaded/src/MadnessInteractiveReloaded/Program.cs:line 49
```

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version 0.50.0

**Additional context**
This is an issue with the `NativeFileDialogExtendedSharp` NuGet package, could be fixed by switching to `NativeFileDialogSharp`, see this: https://github.com/milleniumbug/NativeFileDialogSharp/issues/3

**Comment by Technochips** [comment]
Welp. I've successfully ported the game to use the other NuGet package. But then I fixed the current build by just manually compiling nativefiledialog-extended on my system instead of using the provided libnfd.so file. So that file's the problem.

I'll fix it on the AUR package by just manually building it, that tends to always be better than using pre-compiled blobs.
