### ISSUE TITLE
"System.Exception: External ID is none, but asset not found in any package"

### ISSUE THREAD

**Issue by WUTcappy** [studio-minus/madness-interactive-reloaded#53]
**Describe the bug**
Game crashes on boot, couldn't find something?

**Steps to reproduce**
1. Launch game
2. Crash
**Expected behavior**
I expected to be able to play the game.

**Screenshots or video**
None

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 0.48.3

**Additional context**
Error log

 at Walgelijk.AssetManager.Assets.Validate(GlobalAssetId& id) in C:\Projects\Walgelijk\Walgelijk.AssetManager\Assets.cs:line 391
   at Walgelijk.AssetManager.Assets.LoadDirect[T](GlobalAssetId id) in C:\Projects\Walgelijk\Walgelijk.AssetManager\Assets.cs:line 373
   at MIR.Prefabs.CreateCharacter(Scene scene, CharacterPrefabParams params) in C:\Projects\madness-interactive-reloaded\src\MadnessInteractiveReloaded\Prefabs\Prefabs.cs:line 613
   at MIR.Prefabs.CreatePlayer(Scene scene, Vector2 bottom) in C:\Projects\madness-interactive-reloaded\src\MadnessInteractiveReloaded\Prefabs\Prefabs.cs:line 871
   at MIR.MainMenuSystem.ProcessPlayerCharacter(MainMenuComponent mm) in C:\Projects\madness-interactive-reloaded\src\MadnessInteractiveReloaded\User interface\Systems\MainMenuSystem.cs:line 97
   at MIR.MainMenuSystem.Update() in C:\Projects\madness-interactive-reloaded\src\MadnessInteractiveReloaded\User interface\Systems\MainMenuSystem.cs:line 44
   at Walgelijk.Game.Start() in C:\Projects\Walgelijk\Walgelijk\System\Game.cs:line 213
   at MIR.MadnessInteractiveReloaded..ctor() in C:\Projects\madness-interactive-reloaded\src\MadnessInteractiveReloaded\MadnessInteractiveReloaded.cs:line 211
   at MIR.Program.Main(String mode, String input, String output) in C:\Projects\madness-interactive-reloaded\src\MadnessInteractiveReloaded\Program.cs:line 56

**Comment by mestiez** [comment]
How are you starting the game? Did you unpack the zip?

**Comment by mestiez** [comment]
I updated the engine to print what ID was not found (overdue), so let's see what the issue was

**Comment by Majesticgrey** [comment]
Same issue, i am on Windows 11.
 External ID is none, but asset not found in any package: 0:0
   at Walgelijk.AssetManager.Assets.Validate(GlobalAssetId& id) in C:\Projects\Walgelijk\Walgelijk.AssetManager\Assets.cs:line 402
   at Walgelijk.AssetManager.Assets.LoadDirect[T](GlobalAssetId id) in C:\Projects\Walgelijk\Walgelijk.AssetManager\Assets.cs:line 373
   at MIR.Prefabs.CreateCharacter(Scene scene, CharacterPrefabParams params) in C:\Projects\madness-interactive-reloaded\src\MadnessInteractiveReloaded\Prefabs\Prefabs.cs:line 613
   at MIR.Prefabs.CreatePlayer(Scene scene, Vector2 bottom) in C:\Projects\madness-interactive-reloaded\src\MadnessInteractiveReloaded\Prefabs\Prefabs.cs:line 871
   at MIR.MainMenuSystem.ProcessPlayerCharacter(MainMenuComponent mm) in C:\Projects\madness-interactive-reloaded\src\MadnessInteractiveReloaded\User interface\Systems\MainMenuSystem.cs:line 97
   at MIR.MainMenuSystem.Update() in C:\Projects\madness-interactive-reloaded\src\MadnessInteractiveReloaded\User interface\Systems\MainMenuSystem.cs:line 44
   at Walgelijk.Game.Start() in C:\Projects\Walgelijk\Walgelijk\System\Game.cs:line 213
   at MIR.MadnessInteractiveReloaded..ctor() in C:\Projects\madness-interactive-reloaded\src\MadnessInteractiveReloaded\MadnessInteractiveReloaded.cs:line 211
   at MIR.Program.Main(String mode, String input, String output) in C:\Projects\madness-interactive-reloaded\src\MadnessInteractiveReloaded\Program.cs:line 56

I tried clearing out some files on my C: drive (where it is installed) but that didn't help.
Note that I am using the provided ZIP file version.

**Comment by mestiez** [comment]
Please delete the `player.look` file in the `userdata` folder.
