### ISSUE TITLE
Game is crashing if you enable fullscreen

### ISSUE THREAD

**Issue by fantik86** [studio-minus/madness-interactive-reloaded#68]
**Describe the bug**
Game is crashing if you enable fullscreen, it is crashing when you enabling it, and game crashing if you try to run it again, when main menu GUI is loading 

**Steps to reproduce**
1. Enable fullscreen

**Expected behavior**
I excepted that game will run in fullscreen

**Screenshots or video**
-

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 22h2

**Additional context**
-

**Comment by mestiez** [comment]
Show the crash screen?

**Comment by fantik86** [comment]
Im sorry, i said some things wrong.
1. Game crashes when i trying to run mission "Employee of the month"
2. There is no crash screen, game just closes

**Comment by fantik86** [comment]
Oh, and first cutscene runs without problems, when i click on "Level select" and choosing it, i think you guys just need to debug it

**Comment by fantik86** [comment]
Now im getting HTML crash report when trying to run the game

Unhandled exception occurred

System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')

Stack trace
   at System.SZArrayHelper.get_Item[T](Int32 index)
   at System.Linq.Enumerable.ElementAt[TSource](IEnumerable`1 source, Int32 index)
   at Walgelijk.Utilities.PickRandom[T](IEnumerable`1 collection) in C:\Projects\Walgelijk\Walgelijk\Shared\Utilities.cs:line 223
   at MIR.Registry`1.GetRandomValue() in C:\Projects\madness-interactive-reloaded\src\MadnessInteractiveReloaded\Registries\Registry.cs:line 24
   at MIR.MainMenuSystem.ProcessPlayerCharacter(MainMenuComponent mm) in C:\Projects\madness-interactive-reloaded\src\MadnessInteractiveReloaded\User interface\Systems\MainMenuSystem.cs:line 103
   at MIR.MainMenuSystem.Update() in C:\Projects\madness-interactive-reloaded\src\MadnessInteractiveReloaded\User interface\Systems\MainMenuSystem.cs:line 44
   at Walgelijk.Game.Start() in C:\Projects\Walgelijk\Walgelijk\System\Game.cs:line 213
   at MIR.MadnessInteractiveReloaded..ctor() in C:\Projects\madness-interactive-reloaded\src\MadnessInteractiveReloaded\MadnessInteractiveReloaded.cs:line 211
   at MIR.Program.Main(String mode, String input, String output) in C:\Projects\madness-interactive-reloaded\src\MadnessInteractiveReloaded\Program.cs:line 56

**Comment by 234223452** [comment]
Same problem, but no solution yet.I guess we just wait till they make an update or something
