### ISSUE TITLE
a bug that happens when trying to enter the boss of employee of the month

### ISSUE THREAD

**Issue by amadnesscombatguy** [studio-minus/madness-interactive-reloaded#99]
heres the text of the error
Madness Interactive Reloaded has crashed with crash ID Eemou
Game build: MIR, Version=0.48.3.0, Culture=neutral, PublicKeyToken=null
Engine build: Walgelijk, Version=0.29.0.0, Culture=neutral, PublicKeyToken=null
[Component dump path](file:///C:/Users/16472/AppData/Local/Temp/mir_Eemou_components.md)
[System dump path](file:///C:/Users/16472/AppData/Local/Temp/mir_Eemou_systems.md)
[Log path](file:///C:/Users/16472/AppData/Local/Temp/mir_Eemou.log)
Unhandled exception occurred
System.NullReferenceException: Object reference not set to an instance of an object.
Stack trace
   at Walgelijk.OpenTK.RenderTextureCache.DisposeOf(RenderTextureHandles loaded) in C:\Projects\Walgelijk\Walgelijk.OpenTK\Graphics\RenderTextureCache.cs:line 71
   at Walgelijk.Cache`2.Unload(UnloadedType obj) in C:\Projects\Walgelijk\Walgelijk\Shared\Cache.cs:line 167
   at Walgelijk.OpenTK.OpenTKGraphics.Delete(Object obj) in C:\Projects\Walgelijk\Walgelijk.OpenTK\Graphics\OpenTKGraphics.cs:line 247
   at Walgelijk.RenderTexture.Dispose() in C:\Projects\Walgelijk\Walgelijk\Graphics\RenderTexture.cs:line 119
   at MIR.StampCanvasComponent.Dispose() in C:\Projects\madness-interactive-reloaded\src\MadnessInteractiveReloaded\Graphics\Components\StampCanvasComponent.cs:line 94
   at Walgelijk.FilterComponentCollection.InternalRemoveComponent(Component component) in C:\Projects\Walgelijk\Walgelijk\ECS\Components\FilterComponentCollection.cs:line 267
   at Walgelijk.FilterComponentCollection.SyncBuffers() in C:\Projects\Walgelijk\Walgelijk\ECS\Components\FilterComponentCollection.cs:line 250
   at Walgelijk.Scene.Dispose() in C:\Projects\Walgelijk\Walgelijk\ECS\Scene.cs:line 414
   at Walgelijk.Game.set_Scene(Scene value) in C:\Projects\Walgelijk\Walgelijk\System\Game.cs:line 56
   at MIR.MadnessUtils.<>c__DisplayClass24_1.b__1() in C:\Projects\madness-interactive-reloaded\src\MadnessInteractiveReloaded\Shared\MadnessUtils.cs:line 310
   at MIR.MadnessUtils.<>c__DisplayClass25_0.<g__delay|0>d.MoveNext() in C:\Projects\madness-interactive-reloaded\src\MadnessInteractiveReloaded\Shared\MadnessUtils.cs:line 338
   at Walgelijk.RoutineScheduler.g__advance|5_0(<>c__DisplayClass5_0&) in C:\Projects\Walgelijk\Walgelijk\System\RoutineScheduler.cs:line 82
   at Walgelijk.RoutineScheduler.StepRoutines(Single dt) in C:\Projects\Walgelijk\Walgelijk\System\RoutineScheduler.cs:line 78
   at Walgelijk.Game.Start() in C:\Projects\Walgelijk\Walgelijk\System\Game.cs:line 263
   at MIR.MadnessInteractiveReloaded..ctor() in C:\Projects\madness-interactive-reloaded\src\MadnessInteractiveReloaded\MadnessInteractiveReloaded.cs:line 211
   at MIR.Program.Main(String mode, String input, String output) in C:\Projects\madness-interactive-reloaded\src\MadnessInteractiveReloaded\Program.cs:line 56

**Comment by ionutz799** [comment]
the game crashed because of a NullReferenceException when trying to access/dispose of a texture that wasnt properly initialized this probably happened during the rendering cleanup process.

**Comment by mestiez** [comment]
90% sure this was fixed. If it happens again, open a new issue.
